ppe_hopital_homepage:
    path:     /hello/{name}
    defaults: { _controller: PPEHopitalBundle:Default:index }
    ppe_hopital_accueil:
    path:     /accueil
    defaults: { _controller: PPEHopitalBundle:Default:accueil.html.twig }
    ppe_hopital_untlitled:
    path:     /untlitled
    defaults: { _controller: PPEHopitalBundle:Default:untlitled.html.twig }
