parameters:
#    ppeoc_user.example.class: PPE\OCUserBundle\Example

services:
#    ppeoc_user.example:
#        class: %ppeoc_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
