<?php

namespace PPE\HopitalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RDVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RDVRepository extends EntityRepository
{
}
