<?php

namespace PPE\HopitalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SecretaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretaireRepository extends EntityRepository
{
}
